// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cpa-logo-header/CompactBlack.tsx": () => import("../components/mockups/cpa-logo-header/CompactBlack.tsx"),
  "./components/mockups/cpa-logo-header/Current.tsx": () => import("../components/mockups/cpa-logo-header/Current.tsx"),
  "./components/mockups/cpa-logo-header/MastheadBlack.tsx": () => import("../components/mockups/cpa-logo-header/MastheadBlack.tsx")
};
